# cloudbuild.yaml
substitutions:
  _IMAGE: 'us-central1-docker.pkg.dev/ml-nba-project/nba-docker-repo/nba_project'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull ${_IMAGE}:latest || true']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--cache-from'
      - '${_IMAGE}:latest'
      - '-t'
      - '${_IMAGE}:${SHORT_SHA}'
      - '-t'
      - '${_IMAGE}:latest'
      - '.'

images:
  - '${_IMAGE}:${SHORT_SHA}'
  - '${_IMAGE}:latest'