#!/bin/bash

###############################################################################
# 🛠️  GCP Configuration Setup Helper
# Purpose: Interactive script to configure gcp_config.sh
###############################################################################

echo "=================================================="
echo "🛠️  GCP CONFIGURATION SETUP"
echo "=================================================="
echo ""
echo "This script will help you configure your GCP settings."
echo ""

# Get current GCP project
CURRENT_PROJECT=$(gcloud config get-value project 2>/dev/null)

if [ -n "$CURRENT_PROJECT" ]; then
    echo "📦 Current GCP Project: ${CURRENT_PROJECT}"
    read -p "Use this project? (yes/no): " use_current
    if [ "$use_current" = "yes" ]; then
        PROJECT_ID="$CURRENT_PROJECT"
    else
        read -p "Enter your GCP Project ID: " PROJECT_ID
    fi
else
    read -p "Enter your GCP Project ID: " PROJECT_ID
fi

# Get region
echo ""
echo "🌍 Common regions:"
echo "   - us-central1 (Iowa)"
echo "   - us-east1 (South Carolina)"
echo "   - europe-west1 (Belgium)"
echo "   - asia-northeast1 (Tokyo)"
read -p "Enter your region : " REGION
REGION=${REGION:-us-central1}

# Get bucket name
echo ""
read -p "Enter your Cloud Storage bucket name (without gs://): " BUCKET_NAME

# Get service account
echo ""
SERVICE_ACCOUNTS=$(gcloud iam service-accounts list --project="$PROJECT_ID" --format="value(email)" 2>/dev/null)
if [ -n "$SERVICE_ACCOUNTS" ]; then
    echo "📋 Available service accounts:"
    echo "$SERVICE_ACCOUNTS" | nl
    echo ""
fi
read -p "Enter your service account email: " SERVICE_ACCOUNT

# Get Artifact Registry details
echo ""
read -p "Enter your Artifact Registry repository name: " REPO_NAME
read -p "Enter your Docker image name: " IMAGE_NAME

# Get Training Settings
echo ""
echo "🎯 Training Configuration"
read -p "Enter targets to train (space separated) [points fantasy_points]: " TARGETS
TARGETS=${TARGETS:-points fantasy_points}
read -p "Enable hyperparameter tuning by default? (true/false) [false]: " TUNE_PARAMS
TUNE_PARAMS=${TUNE_PARAMS:-false}

# Get Secret Manager Settings
echo ""
echo "🔑 Secret Manager Configuration"
read -p "Enter secret name for Proxy User [nba-proxy-user]: " NBA_PROXY_USER_SECRET
NBA_PROXY_USER_SECRET=${NBA_PROXY_USER_SECRET:-nba-proxy-user}
read -p "Enter secret name for Proxy Password [nba-proxy-pass]: " NBA_PROXY_PASS_SECRET
NBA_PROXY_PASS_SECRET=${NBA_PROXY_PASS_SECRET:-nba-proxy-pass}
read -p "Enter secret name for Discord webhook URL [discord-webhook-url]: " DISCORD_WEBHOOK_URL_SECRET
DISCORD_WEBHOOK_URL_SECRET=${DISCORD_WEBHOOK_URL_SECRET:-discord-webhook-url}

# Get Git settings
echo ""
echo "📁 Git & Project Configuration"
read -p "Enter your project directory path [~/nba_project_ML]: " PROJECT_DIR
PROJECT_DIR=${PROJECT_DIR:-~/nba_project_ML}
read -p "Enter your development branch [feature/fantsay-points-prediction]: " DEV_BRANCH
DEV_BRANCH=${DEV_BRANCH:-feature/fantsay-points-prediction}
read -p "Enter your production branch [main]: " PROD_BRANCH
PROD_BRANCH=${PROD_BRANCH:-main}

# Confirm
echo ""
echo "=================================================="
echo "📋 CONFIGURATION SUMMARY"
echo "=================================================="
echo ""
echo "Project ID:        ${PROJECT_ID}"
echo "Region:            ${REGION}"
echo "Bucket:            ${BUCKET_NAME}"
echo "Service Account:   ${SERVICE_ACCOUNT}"
echo "Repository:        ${REPO_NAME}"
echo "Image Name:        ${IMAGE_NAME}"
echo ""
echo "Training Settings:"
echo "  Targets:         ${TARGETS}"
echo "  Tuning:          ${TUNE_PARAMS}"
echo ""
echo "Secrets:"
echo "  Proxy User:      ${NBA_PROXY_USER_SECRET}"
echo "  Proxy Pass:      ${NBA_PROXY_PASS_SECRET}"
echo "  Discord Hook:    ${DISCORD_WEBHOOK_URL_SECRET}"
echo ""
echo "Git Settings:"
echo "  Project Dir:     ${PROJECT_DIR}"
echo "  Dev Branch:      ${DEV_BRANCH}"
echo "  Prod Branch:     ${PROD_BRANCH}"
echo ""
echo "Model Paths:"
echo "  Prod Points:     gs://${BUCKET_NAME}/models_trained/prod/points_model.pkl"
echo "  Prod Fantasy:    gs://${BUCKET_NAME}/models_trained/prod/fantasy_points_model.pkl"
echo "  Dev Points:      gs://${BUCKET_NAME}/models_trained/develop/points_model.pkl"
echo "  Dev Fantasy:     gs://${BUCKET_NAME}/models_trained/develop/fantasy_points_model.pkl"
echo ""
read -p "Is this correct? (yes/no): " confirm

if [ "$confirm" != "yes" ]; then
    echo "❌ Configuration cancelled. Run the script again to retry."
    exit 0
fi

# Create config file
echo ""
echo "📝 Writing configuration to scripts/gcp_config.sh..."

cat > scripts/gcp_config.sh << EOF
###############################################################################
# ⚙️  Google Cloud Platform Configuration
# 
# 📝 Auto-generated by setup_gcp_config.sh
# Last updated: $(date)
#
###############################################################################

# 🌐 Google Cloud Project Settings
export PROJECT_ID="${PROJECT_ID}"
export REGION="${REGION}"

# 🪣 Cloud Storage Settings
export BUCKET_NAME="${BUCKET_NAME}"
export MODELS_FOLDER="models_trained"

# 🔐 Service Account
export SERVICE_ACCOUNT="${SERVICE_ACCOUNT}"

# 🐳 Artifact Registry Settings
export REPO_NAME="${REPO_NAME}"
export IMAGE_NAME="${IMAGE_NAME}"

# 🎯 Training Settings
export TARGETS="${TARGETS}"
export TUNE_PARAMS="${TUNE_PARAMS}"

# 🔑 Secret Manager Settings
export NBA_PROXY_USER_SECRET="${NBA_PROXY_USER_SECRET}"
export NBA_PROXY_PASS_SECRET="${NBA_PROXY_PASS_SECRET}"
export DISCORD_WEBHOOK_URL_SECRET="${DISCORD_WEBHOOK_URL_SECRET}"

# 📦 Model Paths (in Cloud Storage)
# Production models (used by production jobs)
export PROD_POINTS_MODEL="gs://\${BUCKET_NAME}/\${MODELS_FOLDER}/prod/points_model.pkl"
export PROD_FANTASY_MODEL="gs://\${BUCKET_NAME}/\${MODELS_FOLDER}/prod/fantasy_points_model.pkl"

# Development models (used by develop jobs for testing)
export DEV_POINTS_MODEL="gs://\${BUCKET_NAME}/\${MODELS_FOLDER}/develop/points_model.pkl"
export DEV_FANTASY_MODEL="gs://\${BUCKET_NAME}/\${MODELS_FOLDER}/develop/fantasy_points_model.pkl"

# 🏷️  Image Tags
export PROD_IMAGE_TAG="latest"
export DEV_IMAGE_TAG="develop"

# 💻 Compute Resources
export MEMORY="4Gi"
export CPU="2"
export TIMEOUT="3600s"
export MAX_RETRIES="1"

# 🔢 NBA Data Settings
export SEASON="2025-26"
export SEASON_TYPE="Regular Season"

# 📁 Git & Project Settings
export PROJECT_DIR="${PROJECT_DIR}"
export DEV_BRANCH="${DEV_BRANCH}"
export PROD_BRANCH="${PROD_BRANCH}"

###############################################################################
# 🛠️  Derived Variables (DO NOT EDIT - Automatically computed)
###############################################################################

# Full image URIs
export PROD_IMAGE_URI="\${REGION}-docker.pkg.dev/\${PROJECT_ID}/\${REPO_NAME}/\${IMAGE_NAME}:\${PROD_IMAGE_TAG}"
export DEV_IMAGE_URI="\${REGION}-docker.pkg.dev/\${PROJECT_ID}/\${REPO_NAME}/\${IMAGE_NAME}:\${DEV_IMAGE_TAG}"

# Base storage path
export STORAGE_BASE="gs://\${BUCKET_NAME}/\${MODELS_FOLDER}"

###############################################################################
# 📋 Configuration Summary Display
###############################################################################

if [ "\$1" = "--show" ]; then
    echo "=================================================="
    echo "⚙️  GCP CONFIGURATION"
    echo "=================================================="
    echo ""
    echo "🌐 Project Settings:"
    echo "   • Project ID: \${PROJECT_ID}"
    echo "   • Region: \${REGION}"
    echo ""
    echo "🎯 Training:"
    echo "   • Targets: \${TARGETS}"
    echo "   • Tuning: \${TUNE_PARAMS}"
    echo ""
    echo "🔑 Secrets:"
    echo "   • Proxy User: \${NBA_PROXY_USER_SECRET}"
    echo "   • Proxy Pass: \${NBA_PROXY_PASS_SECRET}"
    echo "   • Discord Hook: ${DISCORD_WEBHOOK_URL_SECRET}"
    echo ""
    echo "🪣 Storage:"
    echo "   • Bucket: \${BUCKET_NAME}"
    echo "   • Models Folder: \${MODELS_FOLDER}"
    echo ""
    echo "📦 Production Models:"
    echo "   • Points: \${PROD_POINTS_MODEL}"
    echo "   • Fantasy: \${PROD_FANTASY_MODEL}"
    echo ""
    echo "📦 Development Models:"
    echo "   • Points: \${DEV_POINTS_MODEL}"
    echo "   • Fantasy: \${DEV_FANTASY_MODEL}"
    echo ""
    echo "🐳 Container Images:"
    echo "   • Production: \${PROD_IMAGE_URI}"
    echo "   • Development: \${DEV_IMAGE_URI}"
    echo ""
    echo "🔐 Service Account:"
    echo "   \${SERVICE_ACCOUNT}"
    echo ""
    echo "💻 Compute Resources:"
    echo "   • Memory: \${MEMORY}"
    echo "   • CPU: \${CPU}"
    echo "   • Timeout: \${TIMEOUT}"
    echo ""
fi
EOF

chmod +x scripts/gcp_config.sh

echo ""
echo "=================================================="
echo "✅ CONFIGURATION COMPLETE!"
echo "=================================================="
echo ""
echo "✅ Configuration saved to: scripts/gcp_config.sh"
echo ""
echo "🔍 To verify your configuration:"
echo "   source scripts/gcp_config.sh --show"
echo ""
echo "🚀 Next steps:"
echo "   1. Create model folders in Cloud Storage:"
echo "      gsutil mb -p ${PROJECT_ID} -l ${REGION} gs://${BUCKET_NAME}/ 2>/dev/null || true"
echo "      # Note: Folders are virtual in GCS, but you can verify bucket access:"
echo "      gsutil ls gs://${BUCKET_NAME}/"
echo ""
echo "   2. Deploy your image:"
echo "      ./scripts/deploy_develop.sh"
echo ""
echo "   3. Create a development job:"
echo "      ./scripts/create_cloud_run_job_develop.sh"
echo ""
